apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env # Environment variables for frontend
  namespace: frontend
data:
  env.js: |
    (function(window) {
      window["env"] = window["env"] || {};
      window["env"]["baseUrl"] = "https://api.devops-local.com/springMVC";
    })(this);
