# NGINX Controller for is being retired: Use Traefik Ingress Controller instead or Gateway API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Enforce SSL redirection
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.devops-local.com
      secretName: backend-tls # TLS secret for SSL termination
  rules:
    - host: api.devops-local.com
      http:
        paths:
          - path: /springMVC
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
